=== GNOME/gnome-internet-radio-locator/src/gnome-internet-radio-locator-5.0.dtd
<!ATTLIST frequency uri CDATA #REQUIRED >
<!ELEMENT description ( #PCDATA ) >
<!ATTLIST description lang CDATA #REQUIRED >
<!ELEMENT frequency ( #PCDATA ) >
<!ELEMENT email ( #PCDATA ) >
<!ELEMENT location ( #PCDATA ) >
<!ELEMENT gnome_internet_radio_locator ( station+ ) >
<!ATTLIST gnome_internet_radio_locator version NMTOKEN #REQUIRED >
<!ELEMENT station ( frequency | location | description | stream | uri )* >
<!ATTLIST station band CDATA #REQUIRED >
<!ATTLIST station icon CDATA #IMPLIED >
<!ATTLIST station id NMTOKEN #REQUIRED >
<!ATTLIST station lang CDATA #IMPLIED >
<!ATTLIST station name CDATA #REQUIRED >
<!ATTLIST station rank CDATA #REQUIRED >
<!ATTLIST station type CDATA #REQUIRED >
<!ELEMENT uri ( #PCDATA ) >
<!ELEMENT stream EMPTY >
<!ATTLIST stream bitrate CDATA #REQUIRED >
<!ATTLIST stream channels NMTOKEN #IMPLIED >
<!ATTLIST stream codec CDATA #REQUIRED >
<!ATTLIST stream mime CDATA #REQUIRED >
<!ATTLIST stream samplerate CDATA #REQUIRED >
<!ATTLIST stream uri CDATA #REQUIRED >

=== GNOME/gnome-internet-radio-locator/src/gnome-internet-radio-locator.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="https://people.gnome.org/~ole/gnome-internet-radio-locator/gnome-internet-radio-locator.xsl" ?>
<!DOCTYPE gnome_internet_radio_locator SYSTEM "gnome-internet-radio-locator-5.0.dtd">
<gnome_internet_radio_locator version="12.5.0">
  <station band="Online" id="nrkp1pluss" name="NRK P1+" rank="1.0" type="gov">
    <location>Oslo, Norway</location>
    <description lang="nb">NRK P1+ er en av NRKs radiokanaler, som sendes på DAB og som nettradiokanal. NRK P1+ startet sine sendinger 2. oktober 2013 som en del av NRKs heldigitale radiotilbud og radiokanelen erstattet NRK Gull. Av de første programlederne har vært Viggo Valle, Kari Sørbø, Hanne Hoftun, Erik Forfod og Hans-Petter Jacobsen.</description>
    <stream mime="audio/mpeg" uri="http://lyd.nrk.no/nrk_radio_p1pluss_aac_h" codec="MPEG-4 AAC" samplerate="48000 Hz" bitrate="125 kbps" />
    <uri>https://www.nrk.no/informasjon/nrk-p1_-pa-lufta-1.11253656</uri>
  </station>
  <station band="Online" id="nrkp3x" name="NRK P3X" rank="1.0" type="gov">
    <location>Oslo, Norway</location>
    <description lang="nb">NRK P3X er en radiokanal fra NRK, som utelukkende spiller musikk, hovedsakelig hiphop, norsk rap og RnB. Den ble etablert 28. februar 2019. Kanalen ble opprettet med det formål at musikkmiksen skal følges opp mye tettere og oppdateres ukentlig og ved behov, og i større grad løfte frem den norske musikkscenen.</description>
    <stream mime="audio/mpeg" uri="http://lyd.nrk.no/nrk_radio_p3x_aac_h" codec="MPEG-4 AAC" samplerate="48000 Hz" bitrate="125 kbps" />
    <uri>https://www.nrk.no/presse/programomtaler/nrk-p3-styrker-hiphop-tilbudet-1.14450672</uri>
  </station>
  <station band="Online" id="nrksuper" name="NRK Super" rank="1.0" type="gov">
    <location>Oslo, Norway</location>
    <description lang="nb">NRK Super er NRKs tilbud for barn fra 2 til 12 år. Tilbudet består av en TV-kanal som sender fra 06.30 til 19.30, på samme sendefrekvens som NRK3, Norges største nettsted for barn; nrksuper.no, samt en radiokanal som sender på DAB hver dag fra 06 til 21, og døgnkontinuerlig på nettradio i tillegg til en egen app med programarkiv.</description>
    <stream mime="audio/mpeg" uri="http://lyd.nrk.no/nrk_radio_p3x_aac_h" codec="MPEG-4 AAC" samplerate="48000 Hz" bitrate="125 kbps" />
    <uri>https://nrksuper.no/</uri>
  </station>
  <station band="Online" id="nrkfolkemusikk" name="NRK Folkemusikk" rank="1.0" type="gov">
    <location>Oslo, Norway</location>
    <description lang="nb">NRK Folkemusikk er NRKs tiende radiokanal, og var den første norske radiokanalen som bare sendte digitalt via DAB og Internett. Kanalen sender bare musikk, uten programleder. Musikken på kanalen består av både ny og gammel norsk folkemusikk i tillegg til noe verdensmusikk.</description>
    <stream mime="audio/mpeg" uri="http://lyd.nrk.no/nrk_radio_folkemusikk_aac_h" codec="MPEG-4 AAC" samplerate="48000 Hz" bitrate="125 kbps" />
    <uri>https://www.nrk.no/skole/musikkparken/folkemusikken-og-nrk-1.13175858</uri>
  </station>
  <station band="107.2FM" id="nordfjordnærradio" name="Nordfjord Nærradio" rank="1.0" type="org">
    <location>Nordfjord, Norway</location>
    <description lang="nn">Nordfjord Nærradio var stifta i 1987 og var lokaliset på Fjordane Folkehøgskule på Eid. Det var i starten elevar og lærarar på skulen som var drivkrafta bak radioen. Vi hadde fleire studio på skulen før vi flytta ut derifrå. Totalt har vi hatt 6 studio kringom på Eid. Hestnesbygget, Øyane der låsbutikken ligg i dag, og dagens studio Trivselshjørnet i det gamle vegvesen bygget.

    Opp igjennom tida sidan 1987, har det vore mange innom NNR. Vi har hatt fast ansatt redaktør i full stilling på 90 talet, men det synte seg vanskelig å få god økonomi i dette. Så på slutten av 90 talet kom Jon Roar inn som redaktør, noko han er den dag i dag. Rasmus Torvik var og ein av mange primus motorar hos oss. Han har digitalisert det aller meste av våre gamle program før han gjekk bort, og har difor hovedæra for at vi har eit rikhaldig arkiv med program omtrent heilt frå starten av.

    Vi har medarbeidarar frå både Gloppen og Stad kommune, og det var ein lang periode 2 hovudstudio. Eit på Sandane og det andre på Eid. Etter at studioet på Sandane måtte flytte ut frå lokalet vi hadde der, vart det dessverre ikkje funne nokon ny god plass der. Sidan har vi fokusert på å utvikle dagens studio på Eid.

    Radioen gjekk gjennom nokre veldig tunge år etter tusenårsskiftet, og vi var nær med å legge inn årane . Dette klarte vi heldigvis å snu med god innsats og løysingar fra alle involverte i desse tunge åra. I dag kan vi seie at vi driv godt og sunt, takka vere radiobingoen vår

    Radiobingoen har vore og er hovudinntektskjelda til radioen. Og den er populær i heile dekningsområdet vårt. Vi slepp difor å selje reklame for å overleve i dagens radiomarknad.

    I desse dagar (haust 21 og vår 22) har vi oppgradert radioen til og å sende på nett. Dette gjer at vi kan nå lyttarar over heile verda (om vi vil) som har lyst å høyre kjente stemmer frå heimkommunane sine. Samt at vi når stadar som har dårleg dekning på dagens FM sendarar. Vi sender direkte kvar onsdag med radiobingo og kvar fredag med Fredagskveld frå Trivselshjørnet. I tillegg har vi sendingar torsdagar når det er kommunestyremøte i Stad kommune.

    I dag sender vi altså på nett via linken til Radioplayer på framsida vår.

    På FM nettet, har vi 1 hovudsendar på studioet på Eid som sender på 107,2 mhz. I tillegg har vi omformarar på Sandane 104,3 mhz, Hunvikfjellet 106,2 mhz og Davikneset 105,8 mhz. Desse har blitt og vil bli oppgraderte utover i 2022.</description>
    <stream mime="audio/mpeg" uri="https://lyd.nnr1987.no/nnr_hq" codec="MPEG 1 Audio, Layer 3 (MP3)" samplerate="44100 Hz" channels="JntStereo" bitrate="192 kbps" />
    <uri>https://nnr1987.no/</uri>
  </station>
  <station band="102.9FM" id="radiojazzcopenhagen" name="Radio Jazz Copenhagen" rank="1.0" type="com">
    <location>Copenhagen, Denmark</location>
    <description lang="dk">Radio Jazz sender på nettet hele døgnet.  På FM 102,9 Mhz samsender vi mandag til fredag fra 21.00 - 00.00 samt lørdag og søndag i tidsrummet 12.00 - 16.00.  Radio Jazz Copenhagen is broadcasting 24/7 on the web.</description>
    <stream mime="audio/mpeg" uri="http://asima.out.airtime.pro:8000/radiojazzcopenhagen_a" codec="MPEG 1 Audio, Layer 3 (MP3)" samplerate="44100 Hz" channels="JntStereo" bitrate="192 kbps" />
    <uri>http://www.radiojazz.dk/</uri>
  </station>
  <station band="Online" id="bbcradio1" name="BBC - Radio 1" rank="1.0" type="gov">
    <location>United Kingdom</location>
    <stream mime="audio/mpeg" uri="http://stream.live.vc.bbcmedia.co.uk/bbc_radio_one" codec="MPEG 1 Audio, Layer 3 (MP3)" samplerate="24000 Hz" channels="Stereo" bitrate="56 kbps" />
    <uri>http://www.bbc.co.uk/</uri>
  </station>
  <station band="Online" id="bbcradio2" name="BBC - Radio 2" rank="1.0" type="gov">
    <location>United Kingdom</location>
    <stream mime="audio/mpeg" uri="http://stream.live.vc.bbcmedia.co.uk/bbc_radio_two" codec="MPEG 1 Audio, Layer 3 (MP3)" samplerate="24000 Hz" channels="Stereo" bitrate="56 kbps" />
    <uri>http://www.bbc.co.uk/</uri>
  </station>
  <station band="Online" id="bbcradio3" name="BBC - Radio 3" rank="1.0" type="gov">
    <location>United Kingdom</location>
    <stream mime="audio/mpeg" uri="http://stream.live.vc.bbcmedia.co.uk/bbc_radio_three" codec="MPEG 1 Audio, Layer 3 (MP3)" samplerate="24000 Hz" channels="Stereo" bitrate="56 kbps" />
    <uri>http://www.bbc.co.uk/</uri>
  </station>
  <station band="Online" id="bbcradio4" name="BBC - Radio 4" rank="1.0" type="gov">
    <location>United Kingdom</location>
    <stream mime="audio/mpeg" uri="http://stream.live.vc.bbcmedia.co.uk/bbc_radio_fourfm" codec="MPEG 1 Audio, Layer 3 (MP3)" samplerate="24000 Hz" channels="Stereo" bitrate="56 kbps" />
    <uri>http://www.bbc.co.uk/</uri>
  </station>
  <station band="Online" id="bbcradio4lwukonly" name="BBC - Radio 4 LW (UK only)" rank="1.0" type="gov">
    <location>United Kingdom</location>
    <stream mime="audio/mpeg" uri="http://stream.live.vc.bbcmedia.co.uk/bbc_radio_fourlw" codec="MPEG 1 Audio, Layer 3 (MP3)" samplerate="24000 Hz" channels="Stereo" bitrate="56 kbps" />
    <uri>http://www.bbc.co.uk/</uri>
  </station>
  <station band="Online" id="bbcradio4lwnonuk" name="BBC - Radio 4 LW (non-UK)" rank="1.0" type="gov">
    <location>United Kingdom</location>
    <stream mime="audio/mpeg" uri="http://stream.live.vc.bbcmedia.co.uk/bbc_radio_fourlw_online_nonuk" codec="MPEG 1 Audio, Layer 3 (MP3)" samplerate="24000 Hz" channels="Stereo" bitrate="56 kbps" />
    <uri>http://www.bbc.co.uk/</uri>
  </station>
  <station band="Online" id="bbcradio5liveukonly" name="BBC - Radio 5 live (UK only)" rank="1.0" type="gov">
    <location>United Kingdom</location>
    <stream mime="audio/mpeg" uri="http://stream.live.vc.bbcmedia.co.uk/bbc_radio_five_live" codec="MPEG 1 Audio, Layer 3 (MP3)" samplerate="24000 Hz" channels="Stereo" bitrate="56 kbps" />
    <uri>http://www.bbc.co.uk/</uri>
  </station>
  <station band="Online" id="bbcradio5livenonuk" name="BBC - Radio 5 live (non-UK)" rank="1.0" type="gov">
    <location>United Kingdom</location>
    <stream mime="audio/mpeg" uri="http://stream.live.vc.bbcmedia.co.uk/bbc_radio_five_live_online_nonuk" codec="MPEG 1 Audio, Layer 3 (MP3)" samplerate="24000 Hz" channels="Stereo" bitrate="56 kbps" />
    <uri>http://www.bbc.co.uk/</uri>
  </station>
  <station band="Online" id="bbcradio6music" name="BBC - Radio 6 Music" rank="1.0" type="gov">
    <location>United Kingdom</location>
    <stream mime="audio/mpeg" uri="http://stream.live.vc.bbcmedia.co.uk/bbc_6music" codec="MPEG 1 Audio, Layer 3 (MP3)" samplerate="24000 Hz" channels="Stereo" bitrate="56 kbps" />
    <uri>http://www.bbc.co.uk/</uri>
  </station>
